services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: CleanArchitecture
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - application_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management console port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - application_network

networks:
  application_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
